### ISSUE TITLE
Ubios discover fails after restart on UDM

### ISSUE THREAD

**Issue by cleidich** [Control-D-Inc/ctrld#206]
I've noticed that discovery of client names from UnifiOs/Ubios fails on the first run of `ctrld` after my UDM is restarted. This has been happening since at least v1.3.10 of ctrld and v4.0.20 of UnifiOS; although it may have been occurring for longer and I just didn't notice it. Unfortunately I can't confirm the exact start date/versions.

When ctrld starts after a device restart (either a true power off/power on or just a software reboot), I do see an error logged about Ubios discovery failing to initialize:
`{"level":"error","error":"exit status 1","time":"2025-01-06T13:45:20-05:00.759","message":"could not init Ubios discover"}`

If I restart the ctrld daemon, UnifiOS discovery will work properly. I'm positing that this is just a case of the discovery init occurring too early in the boot process although I can't be certain. Perhaps a fix is to just have the init re-attempt every x minutes until successful, etc.

This doesn't cause any resolution issues, but does mean that I get some duplicate clients for that endpoint as the clients get reported using another discovered name (usually via PTR or mDNS) until I restart ctrld, at which point they report using their UbiOS names again.

A full debug log after a recent restart is below; I don't see a lot that says why the discovery init is failing but I am happy to do additional testing and debugging if it helps.

Full log
```
{"level":"info","time":"2025-01-06T13:45:16-05:00.141","message":"starting ctrld v1.3.11"}                              {"level":"info","time":"2025-01-06T13:45:16-05:00.261","message":"os: linux Debian GNU/Linux 11 (bullseye) (4.19.152-ui-alpine)"}                                                                                                               {"level":"debug","time":"2025-01-06T13:45:20-05:00.433","message":"control server started: /var/run/ctrld_control.sock"}
{"level":"debug","time":"2025-01-06T13:45:20-05:00.435","message":"resolving \"dns.controld.com\" using bootstrap DNS [\"76.76.2.22:53\" \"[fe80::201:5cff:fe6b:2a46]:53\"]"}                                                                   {"level":"error","error":"dial udp 76.76.2.22:53: connect: network is unreachable\ndial udp [fe80::201:5cff:fe6b:2a46]:53: connect: invalid argument","time":"2025-01-06T13:45:20-05:00.436","message":"could not lookup \"AAAA\" record for domain \"dns.controld.com\""}                                                                                              {"level":"error","error":"dial udp [fe80::201:5cff:fe6b:2a46]:53: connect: invalid argument\ndial udp 76.76.2.22:53: connect: network is unreachable","time":"2025-01-06T13:45:20-05:00.436","message":"could not lookup \"A\" record for domain \"dns.controld.com\""}                                                                                                 {"level":"warn","time":"2025-01-06T13:45:20-05:00.436","message":"could not resolve bootstrap IPs, retrying..."}        {"level":"debug","time":"2025-01-06T13:45:20-05:00.446","message":"resolving \"dns.controld.com\" using bootstrap DNS [\"76.76.2.22:53\" \"[fe80::201:5cff:fe6b:2a46]:53\"]"}                                                                   {"level":"error","error":"dial udp 76.76.2.22:53: connect: network is unreachable\ndial udp [fe80::201:5cff:fe6b:2a46]:53: connect: invalid argument","time":"2025-01-06T13:45:20-05:00.446","message":"could not lookup \"AAAA\" record for domain \"dns.controld.com\""}
{"level":"error","error":"dial udp 76.76.2.22:53: connect: network is unreachable\ndial udp [fe80::201:5cff:fe6b:2a46]:53: connect: invalid argument","time":"2025-01-06T13:45:20-05:00.446","message":"could not lookup \"A\" record for domain \"dns.controld.com\""}
{"level":"warn","time":"2025-01-06T13:45:20-05:00.447","message":"could not resolve bootstrap IPs, retrying..."}        {"level":"debug","time":"2025-01-06T13:45:20-05:00.481","message":"resolving \"dns.controld.com\" using bootstrap DNS [\"76.76.2.22:53\" \"[fe80::201:5cff:fe6b:2a46]:53\"]"}
{"level":"debug","time":"2025-01-06T13:45:20-05:00.521","message":"got answer from nameserver: 76.76.2.22"}
{"level":"debug","time":"2025-01-06T13:45:20-05:00.545","message":"got answer from nameserver: 76.76.2.22"}
{"level":"debug","time":"2025-01-06T13:45:20-05:00.545","message":"bootstrap IPs: [2606:1a40::22 76.76.2.22]"}
{"level":"info","time":"2025-01-06T13:45:20-05:00.545","message":"bootstrap IPs for upstream.0: [\"2606:1a40::22\" \"76.76.2.22\"]"}
{"level":"debug","time":"2025-01-06T13:45:20-05:00.547","message":"resolving \"dns.controld.com\" using bootstrap DNS [\"76.76.2.22:53\" \"[fe80::201:5cff:fe6b:2a46]:53\"]"}
{"level":"debug","time":"2025-01-06T13:45:20-05:00.574","message":"got answer from nameserver: 76.76.2.22"}
{"level":"debug","time":"2025-01-06T13:45:20-05:00.594","message":"got answer from nameserver: 76.76.2.22"}
{"level":"debug","time":"2025-01-06T13:45:20-05:00.594","message":"bootstrap IPs: [2606:1a40::22 76.76.2.22]"}
{"level":"info","time":"2025-01-06T13:45:20-05:00.594","message":"bootstrap IPs for upstream.1: [\"2606:1a40::22\" \"76.76.2.22\"]"}
{"level":"info","bootstrap_ip":"8.8.8.8","time":"2025-01-06T13:45:20-05:00.594","message":"using bootstrap IP for upstream.2"}
{"level":"info","time":"2025-01-06T13:45:20-05:00.594","message":"starting DNS server on listener.0: 0.0.0.0:5354"}
{"level":"debug","time":"2025-01-06T13:45:20-05:00.595","message":"router setup on start"}
{"level":"debug","time":"2025-01-06T13:45:20-05:00.595","message":"start checking DNS loop"}
{"level":"debug","time":"2025-01-06T13:45:20-05:00.595","message":"skipping external: upstream.0"}
{"level":"debug","time":"2025-01-06T13:45:20-05:00.595","message":"skipping external: upstream.1"}
{"level":"debug","time":"2025-01-06T13:45:20-05:00.595","message":"skipping external: upstream.2"}
{"level":"debug","time":"2025-01-06T13:45:20-05:00.595","message":"end checking DNS loop"}
{"level":"debug","iface":"lo","time":"2025-01-06T13:45:20-05:00.604","message":"Restoring DNS for interface"}
{"level":"error","error":"exit status 1","time":"2025-01-06T13:45:20-05:00.759","message":"could not init Ubios discover"}
```

**Comment by ericnixmd** [comment]
Probably related to this: https://github.com/Control-D-Inc/ctrld/issues/196

With my EFG, it sometimes doesn't provide custom names (from Network) and sometimes it does.

**Comment by yegors** [comment]
Issue reproduced. Will fix.

**Comment by yegors** [comment]
You can try running the dev version using this install command, it should resolve the problem.

```
sh -c 'sh -c "$(curl -sSL https://api.controld.dev/dl)"'
```

**Comment by ericnixmd** [comment]
Thanks. I’ll give it a try. It’s for the shadow console. Do you guys monitor the Barry chats? LOL. I’ve probably had some entertaining chats with it. EricOn Feb 14, 2025, at 4:36 PM, Yegor S ***@***.***> wrote:﻿
  You can try running the dev version using this install command, it should resolve the problem.
sh -c 'sh -c "$(curl -sSL https://api.controld.dev/dl)"'
—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



yegors left a comment (Control-D-Inc/ctrld#206)
You can try running the dev version using this install command, it should resolve the problem.
sh -c 'sh -c "$(curl -sSL https://api.controld.dev/dl)"'

**Comment by yegors** [comment]
How do you install it on a shadow device? I thought there is no SSH there. 

We have the ability to view chat logs, but we never do unless we're troubleshooting something.

**Comment by ericnixmd** [comment]
You can ssh into it. I’ll have to find the IP again when I’m home.  Have to ssh into primary and then ssh into secondary from the primary. On Feb 14, 2025, at 5:06 PM, Yegor S ***@***.***> wrote:﻿
  How do you install it on a shadow device? I thought there is no SSH there.
We have the ability to view chat logs, but we never do unless we're troubleshooting something.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



yegors left a comment (Control-D-Inc/ctrld#206)
How do you install it on a shadow device? I thought there is no SSH there.
We have the ability to view chat logs, but we never do unless we're troubleshooting something.

**Comment by ericnixmd** [comment]
I'm going to unplug the primary console and install via SSH on shadow while primary is down.  Probably best way to install it.

**Comment by cleidich** [comment]
Sorry for the delay in responding but I did have a chance to try this out with the dev version (installed today).

After a restart of the hardware I still get a ubios discover failure, but now there's more detail. Looks like it might just be taking too long for the built-in Mongo instance to come up?

```text
-- Boot f353f0b0a60440ac84120bf1a0f4eb79 --
Mar 01 12:52:15 CL-UDM-Home systemd[1]: Started ctrld.service.
Mar 01 12:52:16 CL-UDM-Home ctrld[5297]: Mar  1 12:52:16.000 WRN unable to create log ipc connection error="dial unix /var/run/ctrld_start.sock: connect: no such file or directory"
Mar 01 12:52:23 CL-UDM-Home ctrld[5297]: Mar  1 12:52:23.792 WRN failed to init Ubios discover error="out: 2025-03-01T12:52:23.780-0500 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27117, in(checking socket for error after poll), reason: Connection refused\n2025-03-01T12:52:23.781-0500 E QUERY    [thread1] Error: couldn't connect to server localhost:27117, connection attempt failed :\nconnect@src/mongo/shell/mongo.js:275:13\n@(connect):1:21\nexception: connect failed\n, err: exit status 1"
```

I also get that "unable to create log ipc connection error" on every start of the service, not just on hardware reboots; but I can't see that it affects anything.

**Comment by cuonglm** [comment]
> Sorry for the delay in responding but I did have a chance to try this out with the dev version (installed today).
> 
> After a restart of the hardware I still get a ubios discover failure, but now there's more detail. Looks like it might just be taking too long for the built-in Mongo instance to come up?
> 
> ```text
> -- Boot f353f0b0a60440ac84120bf1a0f4eb79 --
> Mar 01 12:52:15 CL-UDM-Home systemd[1]: Started ctrld.service.
> Mar 01 12:52:16 CL-UDM-Home ctrld[5297]: Mar  1 12:52:16.000 WRN unable to create log ipc connection error="dial unix /var/run/ctrld_start.sock: connect: no such file or directory"
> Mar 01 12:52:23 CL-UDM-Home ctrld[5297]: Mar  1 12:52:23.792 WRN failed to init Ubios discover error="out: 2025-03-01T12:52:23.780-0500 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27117, in(checking socket for error after poll), reason: Connection refused\n2025-03-01T12:52:23.781-0500 E QUERY    [thread1] Error: couldn't connect to server localhost:27117, connection attempt failed :\nconnect@src/mongo/shell/mongo.js:275:13\n@(connect):1:21\nexception: connect failed\n, err: exit status 1"
> ```
> 
> I also get that "unable to create log ipc connection error" on every start of the service, not just on hardware reboots; but I can't see that it affects anything.

Did you re-install the service or just upgrading new binary?

You need to re-install ctrld service, so new dependency setup could take effects.

**Comment by cleidich** [comment]
> [@cleidich](https://github.com/cleidich) Could you please try v1.4.1, re-install ctrld, and see if the issue is fixed?

I gave this a shot today. My steps were:
1. ran `ctrld service uninstall` and confirmed that the systemd service for ctrld was removed.
2. ran the ctrld install command to install the v1.4.1 release
3. confirmed via `ctrld --version` that I am running v1.4.1
4. reinstalled the service via `ctrld start -c /data/controld/ctrld.toml`

Unfortunately I am still seeing both the ipc connection error and the failed to init Ubios discover error after rebooting the UDM.

I took a look at the systemd unit file for ctrld and it does look like it's supposed to be waiting on mongo:
```text
root@name:~# cat /etc/systemd/system/ctrld.service
[Unit]
Description=A highly configurable, multi-protocol DNS forwarding proxy
ConditionFileIsExecutable=/data/controld/ctrld

Wants=network-online.target
After=network-online.target
Wants=NetworkManager-wait-online.service
After=NetworkManager-wait-online.service
Wants=nss-lookup.target
After=nss-lookup.target
Wants=unifi-mongodb.service
After=unifi-mongodb.service

[Service]
StartLimitInterval=5
StartLimitBurst=10
ExecStart=/data/controld/ctrld "run" "-c" "/data/controld/ctrld.toml" "--iface=auto" "--homedir=/etc/controld"

WorkingDirectory=/etc/controld





Restart=always

RestartSec=120
EnvironmentFile=-/etc/sysconfig/ctrld

[Install]
WantedBy=multi-user.target
```

Perhaps Mongo starts but is still not ready to accept connections, before ctrld starts its discovery?

**Comment by cleidich** [comment]
@ericnixmd - curious to get your feedback/experience if you've tried this, as a fellow Ubiquiti user?

**Comment by cuonglm** [comment]
@cleidich When you did `ctrld clients list`, does the client custom hostname appear?

FYI, v1.4.1 will now allow initial discover to be failed, and later discover iteration will continue querying custom host name from database.

**Comment by cleidich** [comment]
@cuonglm Ah, right you are! I tried another hardware restart, and I did get the errors in the log BUT by the time I checked the `ctrld clients list`, it was properly discovering from ubios. Looks good to me! Thanks for the fix!

**Comment by ericnixmd** [comment]
> [@ericnixmd](https://github.com/ericnixmd) - curious to get your feedback/experience if you've tried this, as a fellow Ubiquiti user?

I uninstalled the CLI so I could test UniFi's DNS logs with the EFG.  Just reinstalled it today and was also able to reinstall it on a shadow gateway (note: you have to clear the web-based TOML config or it will err out at installing).  I restarted EFGs several times today and each time when it came back up, it was correctly reporting clients.  Will continue to monitor, but the restart issue seems to be fixed.  Occasionally in the past I would lose client reporting after a Network upgrade.  Will see what happens when the next Network is released.

Thanks @cuonglm and team for the work on this!
